// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgkI8lWduZm98pNhvYlDDjlX6AXK6M5ok',
    appId: '1:82719094822:web:0fe862cec6b2f8bcdd0ee7',
    messagingSenderId: '82719094822',
    projectId: 'proyectops01',
    authDomain: 'proyectops01.firebaseapp.com',
    storageBucket: 'proyectops01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFdGQNc6IhxkNL1L-DQ4aRUKIWR7IMssg',
    appId: '1:82719094822:android:5cf7d9c3b6d2fefbdd0ee7',
    messagingSenderId: '82719094822',
    projectId: 'proyectops01',
    storageBucket: 'proyectops01.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgkI8lWduZm98pNhvYlDDjlX6AXK6M5ok',
    appId: '1:82719094822:web:0fe862cec6b2f8bcdd0ee7',
    messagingSenderId: '82719094822',
    projectId: 'proyectops01',
    authDomain: 'proyectops01.firebaseapp.com',
    storageBucket: 'proyectops01.firebasestorage.app',
  );

}